"""m8: alerts and disk_total

Revision ID: 227770177a60
Revises: f495654cc04d
Create Date: 2026-08-28 12:40:32.411258
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "227770177a60"
down_revision: str | None = "f495654cc04d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("edge_box_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["edge_box_id"],
            ["edge_boxes.id"],
            name=op.f("fk_alerts_edge_box_id_edge_boxes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_alerts_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(
        "uq_alerts_open",
        "alerts",
        ["site_id", "kind", "subject"],
        unique=True,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.add_column("heartbeats", sa.Column("disk_total_bytes", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("heartbeats", "disk_total_bytes")
    op.drop_index(
        "uq_alerts_open", table_name="alerts", postgresql_where=sa.text("resolved_at IS NULL")
    )
    op.drop_table("alerts")
    # ### end Alembic commands ###
