"""baseline: section 5.1 tables

Revision ID: c5aae3b8d7e1
Revises:
Create Date: 2026-08-27 18:25:38.970446
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "c5aae3b8d7e1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "suspended", "archived", name="site_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
    )
    op.create_table(
        "cameras",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("rtsp_url_encrypted", sa.String(), nullable=True),
        sa.Column("resolution", sa.String(length=16), nullable=False),
        sa.Column("fps_target", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "online", "offline", "needs_recalibration", name="camera_status"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("credentials_ref", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "resolution ~ '^[0-9]+x[0-9]+$'", name=op.f("ck_cameras_resolution_shape")
        ),
        sa.CheckConstraint("fps_target > 0", name=op.f("ck_cameras_fps_target_positive")),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_cameras_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cameras")),
    )
    op.create_table(
        "day_annotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("event", "weather", "closure", "maintenance", name="day_annotation_kind"),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("exclude_from_baseline", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_day_annotations_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_day_annotations")),
    )
    op.create_table(
        "occupants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("contact_phone", sa.String(length=64), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_occupants_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occupants")),
    )
    op.create_table(
        "site_totals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_people", sa.Integer(), nullable=False),
        sa.Column("active_cameras", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "total_people >= 0 AND active_cameras >= 0",
            name=op.f("ck_site_totals_totals_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_site_totals_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_totals")),
        sa.UniqueConstraint("site_id", "bucket_start", name="site_bucket"),
    )
    op.create_table(
        "spaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("stall", "table", "patio", "corridor", "entrance", name="space_kind"),
            nullable=False,
        ),
        sa.Column("parent_space_id", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_space_id"],
            ["spaces.id"],
            name=op.f("fk_spaces_parent_space_id_spaces"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_spaces_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spaces")),
    )
    op.create_table(
        "tenancies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("occupant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("permanent", "recurring", "one_off", name="tenancy_kind"),
            nullable=False,
        ),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("recurrence_rule", sa.String(length=500), nullable=True),
        sa.Column("daily_start_time", sa.Time(), nullable=True),
        sa.Column("daily_end_time", sa.Time(), nullable=True),
        sa.Column("rate_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "rate_period",
            sa.Enum("day", "week", "month", "percent_of_sales", name="rate_period"),
            nullable=True,
        ),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'recurring') = (recurrence_rule IS NOT NULL)",
            name=op.f("ck_tenancies_recurrence_rule_iff_recurring"),
        ),
        sa.CheckConstraint(
            "(daily_start_time IS NULL) = (daily_end_time IS NULL)",
            name=op.f("ck_tenancies_daily_window_paired"),
        ),
        sa.CheckConstraint(
            "ends_on IS NULL OR ends_on >= starts_on",
            name=op.f("ck_tenancies_tenancy_range_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["occupant_id"],
            ["occupants.id"],
            name=op.f("fk_tenancies_occupant_id_occupants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_tenancies_space_id_spaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenancies")),
    )
    op.create_table(
        "zone_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.Uuid(), nullable=False),
        sa.Column("polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_zone_versions_effective_range_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
            name=op.f("fk_zone_versions_camera_id_cameras"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
            name=op.f("fk_zone_versions_space_id_spaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone_versions")),
    )
    op.create_index(
        "uq_zone_versions_open_primary",
        "zone_versions",
        ["space_id"],
        unique=True,
        postgresql_where=sa.text("is_primary AND effective_to IS NULL"),
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("zone_version_id", sa.Uuid(), nullable=False),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bucket_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entries", sa.Integer(), nullable=False),
        sa.Column("exits", sa.Integer(), nullable=False),
        sa.Column("peak_occupancy", sa.Integer(), nullable=False),
        sa.Column("occupied_seconds", sa.Float(), nullable=False),
        sa.Column("dwell_p50_seconds", sa.Float(), nullable=False),
        sa.Column("dwell_p90_seconds", sa.Float(), nullable=False),
        sa.Column("passersby", sa.Integer(), nullable=False),
        sa.Column("capture_events", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "bucket_end > bucket_start", name=op.f("ck_observations_bucket_range_ordered")
        ),
        sa.CheckConstraint(
            "capture_events <= entries", name=op.f("ck_observations_capture_events_within_entries")
        ),
        sa.CheckConstraint(
            "entries >= 0 AND exits >= 0 AND peak_occupancy >= 0 AND passersby >= 0 AND capture_events >= 0 AND occupied_seconds >= 0 AND dwell_p50_seconds >= 0 AND dwell_p90_seconds >= 0",
            name=op.f("ck_observations_counts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_version_id"],
            ["zone_versions.id"],
            name=op.f("fk_observations_zone_version_id_zone_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint("zone_version_id", "bucket_start", name="zone_version_bucket"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("observations")
    op.drop_index(
        "uq_zone_versions_open_primary",
        table_name="zone_versions",
        postgresql_where=sa.text("is_primary AND effective_to IS NULL"),
    )
    op.drop_table("zone_versions")
    op.drop_table("tenancies")
    op.drop_table("spaces")
    op.drop_table("site_totals")
    op.drop_table("occupants")
    op.drop_table("day_annotations")
    op.drop_table("cameras")
    op.drop_table("sites")
    for enum_name in (
        "site_status",
        "camera_status",
        "space_kind",
        "tenancy_kind",
        "rate_period",
        "day_annotation_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
