"""m6: operator users

Revision ID: f495654cc04d
Revises: efb85baefcea
Create Date: 2026-08-28 10:18:47.758400
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "f495654cc04d"
down_revision: str | None = "efb85baefcea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_users")),
        sa.UniqueConstraint("email", name=op.f("uq_operator_users_email")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_operator_users_token_hash")),
    )
    op.create_table(
        "operator_user_sites",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_operator_user_sites_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["operator_users.id"],
            name=op.f("fk_operator_user_sites_user_id_operator_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "site_id", name=op.f("pk_operator_user_sites")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operator_user_sites")
    op.drop_table("operator_users")
    # ### end Alembic commands ###
